data_path: ./data/era5_240/full/
wandb_dir: ./wandblogs/
wandb_mode: offline

precision: 16-mixed
batch_size: 1
gpus: 4
cpus: 3

manual_requeue: True

folder: ./sblogs/${name}/

launcher:
    cpus_per_task: 4
    gpus_per_node: ${eval:'min(${cluster.gpus}, 8)'}
    nodes: ${eval:'1 + (${cluster.gpus}-1) // 8'}
    tasks_per_node: ${eval:'min(${cluster.gpus}, 8)'}
    mem_gb: ${eval:'32 * min(${cluster.gpus}, 8)'}
    timeout_min: 1440
    name: ${name}
    slurm_constraint: 
    slurm_account: 
    slurm_additional_parameters:
      hint: nomultithread
    slurm_srun_args:
      - "--cpu-bind=none"
      - "--mem-bind=none"